name: bytebot

services:
  bytebot-desktop:
    # Build from source
    build:
      context: ../../
      dockerfile: infrastructure/docker/Dockerfile
    # Use pre-built image
    image: ghcr.io/bytebot-ai/bytebot:edge
    shm_size: "2g"
    container_name: bytebot-desktop
    restart: unless-stopped
    hostname: computer
    privileged: true
    ports:
      - "9990:9990" # bytebotd service
      - "5900:5900" # VNC display
      - "6080:6080" # noVNC client
      - "6081:6081" # noVNC HTTP proxy
    environment:
      - DISPLAY=:0
    networks:
      - bytebot-network

  postgres:
    image: postgres:16-alpine
    container_name: bytebot-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=bytebotdb
    networks:
      - bytebot-network
    volumes:
      - postgres_data:/var/lib/postgresql/data

  bytebot-agent:
    build:
      context: ../../packages/
      dockerfile: bytebot-agent/Dockerfile
    container_name: bytebot-agent
    restart: unless-stopped
    ports:
      - "9991:9991"
    environment:
      - DATABASE_URL=${DATABASE_URL:-postgresql://postgres:postgres@postgres:5432/bytebotdb}
      - BYTEBOT_DESKTOP_BASE_URL=${BYTEBOT_DESKTOP_BASE_URL:-http://bytebot-desktop:9990}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
    depends_on:
      - postgres
    networks:
      - bytebot-network

  bytebot-ui:
    build:
      context: ../../packages/
      dockerfile: bytebot-ui/Dockerfile
      args:
        - NEXT_PUBLIC_BYTEBOT_AGENT_BASE_URL=${BYTEBOT_AGENT_BASE_URL:-http://localhost:9991}
        - NEXT_PUBLIC_BYTEBOT_DESKTOP_VNC_URL=${BYTEBOT_DESKTOP_VNC_URL:-ws://localhost:6080}
    container_name: bytebot-ui
    restart: unless-stopped
    ports:
      - "9992:9992"
    environment:
      - NODE_ENV=production
    depends_on:
      - bytebot-agent
    networks:
      - bytebot-network

networks:
  bytebot-network:
    driver: bridge

volumes:
  postgres_data:
