[tool.poetry]
name = "bytebot-ai-agent"
version = "0.1.0"
description = "AI agent service for Bytebot Python"
authors = ["Bytebot Team <support@bytebot.ai>"]
packages = [{include = "ai_agent", from = "src"}]

[tool.poetry.dependencies]
python = "^3.11"
fastapi = "^0.104.0"
uvicorn = {extras = ["standard"], version = "^0.24.0"}
pydantic = "^2.5.0"
sqlalchemy = "^2.0.0"
# AI Provider SDKs
anthropic = "^0.39.0"
openai = "^1.3.0"
google-generativeai = "^0.3.0"
# HTTP Client
httpx = "^0.25.0"
# Background Tasks
apscheduler = "^3.10.4"
# Dependency Injection
dependency-injector = "^4.41.0"
# Shared package
bytebot-shared = {path = "../shared", develop = true}

[tool.poetry.group.dev.dependencies]
pytest = "^7.4.0"
pytest-asyncio = "^0.21.0"
pytest-mock = "^3.12.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"