[tool.poetry]
name = "bytebot-computer-control"
version = "0.1.0"
description = "Computer control service for Bytebot Python"
authors = ["Bytebot Team <support@bytebot.ai>"]
packages = [{include = "computer_control", from = "src"}]

[tool.poetry.dependencies]
python = "^3.11"
fastapi = "^0.104.0"
uvicorn = {extras = ["standard"], version = "^0.24.0"}
pyautogui = "^0.9.54"
pynput = "^1.7.6"
pillow = "^10.1.0"
python-socketio = "^5.10.0"
websockets = "^12.0"
pydantic = "^2.5.0"
bytebot-shared = {path = "../shared", develop = true}

[tool.poetry.group.dev.dependencies]
pytest = "^7.4.0"
pytest-asyncio = "^0.21.0"
pytest-mock = "^3.12.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"